name: Enarx Standard Tests
# Automated testing run on all commits.

on: [pull_request]

jobs:
  # Ensure the testing infrastructure is working as intended.
  sanity-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sanity-check test
      run: true

  # Enforce correct fields in Cargo.toml files.
  cargo-toml-tests:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
    
    # Ensure Cargo edition is correct.
    - name: Cargo edition
      run: .tests/cargo-edition

  no-merge-commits:
    runs-on: ubuntu-latest
    container: quay.io/enarx/fedora-test
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    # Ensure pull requests do not contain merge commits.
    - name: No merge commits
      # Merge commits have two parent commits. This command iterates through
      # all commits added by the PR (everything since the base ref) and fails
      # if it finds multiple parents. If all commits only have one, it exits 
      # successfully.
      run: git rev-list origin/${{ github.base_ref }}.. | xargs -n1 -I{} sh -c '! git rev-parse {}^2'
