name: misc

on: [pull_request]

jobs:
  # Miscellaneous organizational tests.
  misc-eof:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    # Ensure all code-related files have a newline at end of file.
    - name: All code files have a newline at EOF
      run: .tests/misc-eof

  # Enforce correct license files and headers.
  misc-licenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Ensure that all crates have a top-level Apache 2.0 license.
    - name: Crate-level licenses present
      run: .tests/misc-licenses-crate

    # Ensure all .rs files have an Apache 2.0 SPDX license ID.
    - name: All .rs files have SPDX IDs
      run: .tests/misc-licenses-rs-spdx

  # Ensure there are no merge commits present.
  misc-merge-commits:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: No merge commits
      # Merge commits have two parent commits. This command iterates through
      # all commits added by the PR (everything since the base ref) and fails
      # if it finds multiple parents. If all commits only have one, it exits 
      # successfully.
      run: git rev-list origin/master.. | xargs -n1 -I{} sh -c '! git rev-parse {}^2'
